import 'package:flutter/material.dart';

class ModuleStrings {
  const ModuleStrings._();

  static String text(BuildContext context, String key) {
    final language = Localizations.localeOf(context).languageCode;
    return _values[language]?[key] ?? _values['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'events': 'Events',
      'events_load_failed': 'Events could not be loaded. Pull down to try again.',
      'no_events': 'No upcoming events are available.',
      'youth_event': 'Youth event',
      'courses': 'Discipleship Courses',
      'courses_load_failed': 'Courses could not be loaded. Pull down to try again.',
      'no_courses': 'No discipleship courses are available yet.',
      'discipleship_course': 'Discipleship Course',
      'for_all_ages': 'For all age groups',
      'for_age': 'For {age}',
      'notifications': 'Notifications',
      'notifications_load_failed': 'Notifications could not be loaded. Pull down to try again.',
      'no_notifications': 'You have no notifications.',
      'notification': 'Notification',
      'notification_update_failed': 'Could not update the notification.',
      'safety_center': 'Safety Centre',
      'report_safety_concern': 'Report a safety concern',
      'safety_intro': 'Use this form to report inappropriate content, a user, a Life Group, media item or prayer request for safeguarding review.',
      'sign_in_report': 'Please sign in before submitting a safeguarding report.',
      'report_submitted': 'Report submitted for review.',
      'report_failed': 'The report could not be submitted. Please try again.',
      'reporting_what': 'What are you reporting?',
      'content': 'Content',
      'user': 'User',
      'life_group': 'Life Group',
      'media_resource': 'Media resource',
      'prayer_request': 'Prayer request',
      'item_user_id': 'Item or user ID',
      'item_user_id_help': 'Use the ID shown on the relevant item or profile.',
      'valid_id': 'Enter a valid ID.',
      'reason': 'Reason',
      'report_reason_required': 'Tell us why you are reporting this.',
      'additional_details': 'Additional details (optional)',
      'submitting': 'Submitting...',
      'submit_report': 'Submit report',
      'blocked_accounts': 'Blocked accounts',
      'sign_in_blocked': 'Sign in to view and manage blocked accounts.',
      'blocked_load_failed': 'Blocked accounts could not be loaded.',
      'no_blocked_accounts': 'You have not blocked any accounts.',
      'blocked_user': 'Blocked user',
      'unblock': 'Unblock',
      'user_unblocked': 'User unblocked.',
    },
    'lg': {
      'events': 'Emikolo',
      'events_load_failed': 'Emikolo tegisobodde kutikkibwa. Sika wansi oddemu ogezeeko.',
      'no_events': 'Tewali mikolo gijja giriwo kati.',
      'youth_event': 'Omukolo gw’abavubuka',
      'courses': 'Amasomo g’Okuyigirizibwa',
      'courses_load_failed': 'Amasomo tegansobodde kutikkibwa. Sika wansi oddemu ogezeeko.',
      'no_courses': 'Tewali masomo ga kuyigirizibwa galiwo kati.',
      'discipleship_course': 'Essomo ly’Okuyigirizibwa',
      'for_all_ages': 'Lya myaka gyonna',
      'for_age': 'Lya {age}',
      'notifications': 'Obubaka',
      'notifications_load_failed': 'Obubaka tebusobodde kutikkibwa. Sika wansi oddemu ogezeeko.',
      'no_notifications': 'Tolina bubaka bupya.',
      'notification': 'Obubaka',
      'notification_update_failed': 'Obubaka tebusobodde kulongoosebwa.',
      'safety_center': 'Ekifo ky’Obukuumi',
      'report_safety_concern': 'Loopa ekikweraliikiriza ku bukuumi',
      'safety_intro': 'Kozesa foomu eno okuloopa ebitali birungi, omuntu, ekibiina ky’obulamu, eby’amawulire oba okusaba bisobole okwekebejjebwa olw’obukuumi.',
      'sign_in_report': 'Yingira mu akawunti nga tonnaweereza lipoota y’obukuumi.',
      'report_submitted': 'Lipoota eweerezeddwa okwekebejjebwa.',
      'report_failed': 'Lipoota tesobodde kuweerezebwa. Ddamu ogezeeko.',
      'reporting_what': 'Kiki ky’oloopa?',
      'content': 'Ebiri ku mukutu',
      'user': 'Omukozesa',
      'life_group': 'Ekibiina ky’Obulamu',
      'media_resource': 'Eky’amawulire',
      'prayer_request': 'Okusaba',
      'item_user_id': 'ID y’ekintu oba omukozesa',
      'item_user_id_help': 'Kozesa ID eragiddwa ku kintu oba ku bikukwatako.',
      'valid_id': 'Teekamu ID entuufu.',
      'reason': 'Ensonga',
      'report_reason_required': 'Tubuulire lwaki oloopa kino.',
      'additional_details': 'Ebisingawo (si bya buwaze)',
      'submitting': 'Kiweerezebwa...',
      'submit_report': 'Weereza lipoota',
      'blocked_accounts': 'Akawunti z’ozibye',
      'sign_in_blocked': 'Yingira olabe era oddukanye akawunti z’ozibye.',
      'blocked_load_failed': 'Akawunti ezizibiddwa tezisobodde kutikkibwa.',
      'no_blocked_accounts': 'Tonnaziba akawunti yonna.',
      'blocked_user': 'Omukozesa azibiddwa',
      'unblock': 'Ggyawo okuziba',
      'user_unblocked': 'Omukozesa aggiddwako okuziba.',
    },
  };
}
